"""Apple Music REST connector for Palantir Foundry data ingestion.

Fetches a user's library playlists and tracks from the Apple Music API and
yields them as plain dicts suitable for writing to Foundry datasets.

Auth:
    Developer token — generated by :mod:`connector.auth.musickit_auth`.
    User token      — OAuth Music User Token obtained separately via MusicKit JS
                      or Apple's authorization flow. Pass as ``user_token=``.

Rate limits:
    Apple enforces ~100 requests/hour on personal-library endpoints.
    This module retries on HTTP 429 with exponential back-off and raises
    ``RateLimitError`` if the retry budget is exhausted.
"""

from __future__ import annotations

import time
import logging
from typing import Any, Generator

import requests

from connector.auth.musickit_auth import get_auth_headers

logger = logging.getLogger(__name__)

_BASE_URL = "https://api.music.apple.com/v1"
_PAGE_LIMIT = 100          # Apple's maximum per-page item count
_MAX_RETRIES = 5           # attempts before giving up on a 429
_BACKOFF_BASE = 2.0        # seconds; doubles each retry


class RateLimitError(Exception):
    """Raised when the Apple Music API 429 retry budget is exhausted."""


class AppleMusicConnector:
    """Thin REST client for the Apple Music personal-library endpoints.

    Args:
        user_token: Music User Token obtained via the Apple OAuth / MusicKit
            JS flow. Required for personal-library endpoints.
        team_id: Apple Developer Team ID. Falls back to ``APPLE_TEAM_ID`` env.
        key_id: MusicKit Key ID. Falls back to ``APPLE_KEY_ID`` env.
        key_path: Path to the .p8 private key file. Falls back to env /
            default naming convention in ``connector/auth/``.
        session: Optional pre-configured :class:`requests.Session`. Useful
            for injecting a mock in tests.

    Example::

        connector = AppleMusicConnector(user_token="<music-user-token>")
        for playlist in connector.iter_playlists():
            print(playlist["id"], playlist["attributes"]["name"])
    """

    def __init__(
        self,
        user_token: str,
        team_id: str | None = None,
        key_id: str | None = None,
        key_path: str | None = None,
        session: requests.Session | None = None,
    ) -> None:
        self._user_token = user_token
        self._team_id = team_id
        self._key_id = key_id
        self._key_path = key_path
        self._session = session or requests.Session()
        self._refresh_auth_headers()

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _refresh_auth_headers(self) -> None:
        """Re-generate developer token and update session headers."""
        dev_headers = get_auth_headers(
            team_id=self._team_id,
            key_id=self._key_id,
            key_path=self._key_path,
        )
        self._session.headers.update(
            {
                **dev_headers,
                "Music-User-Token": self._user_token,
                "Content-Type": "application/json",
            }
        )

    def _get(
        self, path: str, params: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        """Execute a GET request with 429-aware retry logic.

        Args:
            path: API path relative to ``_BASE_URL``, e.g.
                ``/me/library/playlists``.
            params: Optional query parameters.

        Returns:
            Parsed JSON response body.

        Raises:
            RateLimitError: After ``_MAX_RETRIES`` consecutive 429 responses.
            requests.HTTPError: For non-429 HTTP errors.
        """
        url = f"{_BASE_URL}{path}"
        for attempt in range(_MAX_RETRIES):
            response = self._session.get(url, params=params)

            if response.status_code == 429:
                wait = _BACKOFF_BASE ** attempt
                logger.warning(
                    "Rate limited by Apple Music API (attempt %d/%d). "
                    "Retrying in %.1fs.",
                    attempt + 1,
                    _MAX_RETRIES,
                    wait,
                )
                time.sleep(wait)
                continue

            if response.status_code == 401:
                # Developer token may have expired mid-run; refresh once.
                logger.info("401 received — refreshing developer token.")
                self._refresh_auth_headers()
                response = self._session.get(url, params=params)

            response.raise_for_status()
            return response.json()

        raise RateLimitError(
            f"Apple Music API returned 429 after {_MAX_RETRIES} retries for {url}. "
            "Consider spacing out requests or waiting before retrying."
        )

    def _paginate(
        self, path: str, extra_params: dict[str, Any] | None = None
    ) -> Generator[dict[str, Any], None, None]:
        """Yield every item from a paginated Apple Music endpoint.

        Handles ``next`` cursor pagination automatically.

        Args:
            path: API path relative to ``_BASE_URL``.
            extra_params: Additional query parameters (merged with pagination).

        Yields:
            Individual resource dicts from the ``data`` array.
        """
        params: dict[str, Any] = {"limit": _PAGE_LIMIT, **(extra_params or {})}
        offset = 0

        while True:
            params["offset"] = offset
            body = self._get(path, params=params)
            items: list[dict[str, Any]] = body.get("data", [])

            yield from items

            # Apple returns a ``next`` key when more pages exist.
            if not body.get("next"):
                break

            offset += len(items)
            logger.debug("Fetched %d items from %s (offset=%d).", len(items), path, offset)

    # ------------------------------------------------------------------
    # Public API — read (Phase 1)
    # ------------------------------------------------------------------

    def iter_playlists(self) -> Generator[dict[str, Any], None, None]:
        """Yield all playlists in the user's Apple Music library.

        Yields:
            Apple Music playlist resource dicts, e.g.::

                {
                    "id": "p.AbCdEfGh",
                    "type": "library-playlists",
                    "attributes": {
                        "name": "My Playlist",
                        "description": {...},
                        "lastModifiedDate": "2024-01-15T12:00:00Z",
                        "trackCount": 47,
                    }
                }
        """
        yield from self._paginate("/me/library/playlists")

    def iter_playlist_tracks(
        self, playlist_id: str
    ) -> Generator[dict[str, Any], None, None]:
        """Yield all tracks in a single playlist.

        Args:
            playlist_id: Apple Music library playlist ID (e.g. ``"p.AbCdEfGh"``).

        Yields:
            Apple Music library-song resource dicts, e.g.::

                {
                    "id": "i.AbCdEfGh",
                    "type": "library-songs",
                    "attributes": {
                        "name": "Song Title",
                        "artistName": "Artist",
                        "albumName": "Album",
                        "durationInMillis": 210000,
                        "artwork": {"url": "https://.../{w}x{h}bb.jpg"},
                        "url": "https://music.apple.com/...",
                    }
                }
        """
        yield from self._paginate(f"/me/library/playlists/{playlist_id}/tracks")

    def fetch_all_library(
        self,
    ) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
        """Fetch every playlist and every track in the user's library.

        Convenience method for the Foundry ingestion pipeline.  Deduplicates
        tracks that appear in multiple playlists at the resource level while
        preserving playlist membership metadata.

        Returns:
            A two-tuple ``(playlists, memberships)`` where:

            - ``playlists`` — list of playlist dicts with a ``track_ids`` key
              appended.
            - ``memberships`` — list of ``{playlist_id, track_id, position}``
              dicts representing the ``belongs_to`` relationship.
        """
        playlists: list[dict[str, Any]] = []
        memberships: list[dict[str, Any]] = []

        for playlist in self.iter_playlists():
            playlist_id = playlist["id"]
            tracks = list(self.iter_playlist_tracks(playlist_id))

            playlist["track_ids"] = [t["id"] for t in tracks]
            playlists.append(playlist)

            for position, track in enumerate(tracks):
                memberships.append(
                    {
                        "playlist_id": playlist_id,
                        "track_id": track["id"],
                        "position": position,
                    }
                )

        logger.info(
            "Fetched %d playlists, %d membership rows.",
            len(playlists),
            len(memberships),
        )
        return playlists, memberships
